### ISSUE TITLE
eval_configs.yaml is missing 

### ISSUE THREAD

**Issue by EEElisa** [Zhou-Zoey/RMB-Reward-Model-Benchmark#3]
Hey, could you upload the config files for evaluation? Thanks!

**Comment by Zhou-Zoey** [comment]
sorry... but what does the eval_configs.yaml refer to?

**Comment by EEElisa** [comment]
oh it's line 159 of my_run_rm.py 
`    model_config = load_config('../RMB-Reward-Model-Benchmark/eval/scripts/configs/eval_configs.yaml')`
Would it be available?

**Comment by Zhou-Zoey** [comment]
Sorry for the missing file, we will fix it as soon as possible

**Comment by Zhou-Zoey** [comment]
Hi, eval config has been uploaded
